export const FETCH_PRESENTATION_REQUEST = 'FETCH_PRESENTATION_REQUEST'
export const FETCH_PRESENTATION_SUCCESS = 'FETCH_PRESENTATION_SUCCESS'
export const FETCH_PRESENTATION_FAILURE = 'FETCH_PRESENTATION_FAILURE'

export const UPDATE_PRESENTATION_REQUEST = 'UPDATE_PRESENTATION_REQUEST'
export const UPDATE_PRESENTATION_SUCCESS = 'UPDATE_PRESENTATION_SUCCESS'
export const UPDATE_PRESENTATION_FAILURE = 'UPDATE_PRESENTATION_FAILURE'
